### ISSUE TITLE
No crafting recipes for the blocks

### ISSUE THREAD

**Issue by FraukeS** [Ommina/WallpaperCraft#1]
I have recipes in JEI for all the "Press" items,  but no way to craft the wallpaper blocks.

I've tried combining the presses with blocks of stone, terracotta, glass and wood without success.
Clicking the press on a placed block also doesn't work.

Hardened clay no longer exists,  it is now called terracotta,  but the old recipe of 3x3 doesn't work either.

Using:
Walpaper Craft 1.14.4-1.0.2
Minecraft 1.14.4
Forge 28.0.45

**Comment by FraukeS** [comment]
Looking through the source code I found the recipe to make wallpaper blocks.   It also exists in JEI,  but it is impossible to guess which of the 2280 possible blocks is the one to start with.  
Recipes for altering pattern and colour still don't exist in JEI

I left a comment on the curseforge page with the starting recipe,  so that others can find it without going through the source.

**Comment by Ommina** [comment]
If a WallpaperCraft block is selected, JEI _should_ be showing the base block as the sole possible crafting block, along with three cycling presses.  Is this not what you're seeing in game?  I went this route for the very reason that hoping to find the correct block through a (random?) cycling list of 2000+ items is... not a good experience.

I'll add the base block recipe to the CurseForge project description, but a player's first stop is going to be JEI.  If that's not doing it, I may need to find an alternative solution.

**Comment by FraukeS** [comment]
The base block shows 2 recipes,  the other blocks show nothing in JEI.  The recipes for them do work once you know how to craft the blocks.
