### ISSUE TITLE
1.18.2?

### ISSUE THREAD

**Issue by AndyKitty8** [Ommina/WallpaperCraft#11]
Does this mod work on version 1.18.2? Based on the curseforge files it looks like it just works on 1.18.1. I don’t know how different the 2 versions are so I’m not sure what to do.

**Comment by Ommina** [comment]
A previous poster on the CurseForge page suggested it worked with 1.18.2, so I believed him.

Apparently I'll have to stop playing Enigmatica 6 and check for myself.

**Comment by Ommina** [comment]
I did take some time to check -- the current file works with 1.18.2 without changes.  I've updated the CurseForge files to reflect this.
