### ISSUE TITLE
Breaking clay in 1.16

### ISSUE THREAD

**Issue by Sumneer** [Ommina/WallpaperCraft#5]
You can't use any tools to speed up the process of breaking the clay pattern block, I am not sure if this is intentional but it would definitely be more quality of life if you were able to speed up this process.

**Comment by Ommina** [comment]
You're wholly right, harvesting clay (and tinted glass) is way too slow.

There is (perhaps was) some weirdness surrounding harvest levels and tools in Forge for 1.16.1 that may be at play here.  It may be fixed there.  Or it may be something I need to do instead.

I'll look into it.

**Comment by Ommina** [comment]
OK, turns out it is 'both'.

For Forge, you will require 32.0.55 or greater.  However, I also need to make minor changes on my end.

I'm going to take the opportunity to change wood planks to use an axe, but will have a new build on CurseForge by the end of the day.
