### ISSUE TITLE
Minecraft crash on loading screen

### ISSUE THREAD

**Issue by Blugori** [Ommina/WallpaperCraft#9]
Whenever I try to start minecraft with Wallpaper, the game crash in the loading screen

Minecraft ver : 1.16.3
Forge : 34.1.33
WallpaperCraft : 1.4.5

I'm using a lot of mod, it might come from incompatibilities

[crash-2020-10-30_22.44.52-client.txt](https://github.com/Ommina/WallpaperCraft/files/5467814/crash-2020-10-30_22.44.52-client.txt)
[debug.zip](https://github.com/Ommina/WallpaperCraft/files/5467816/debug.zip)
[latest.zip](https://github.com/Ommina/WallpaperCraft/files/5467818/latest.zip)

Best regards

**Comment by Ommina** [comment]
Hm.  There is no mention of Wallpapercraft in the crash report -- the crash report is complaining about missing particles for "Straw Golems".  However, I did fix a crash in 1.4.5 yesterday (see #8), so it is possible that one mod is hiding a problem with the other.

In either case, try version 1.4.6 and see if that resolves the crash.

**Comment by Blugori** [comment]
It worked fine ! thank you :3
